version: '3.8'

services:
   scc413-nifi:
      image: apache/nifi:1.17.0
      ports:
        - '8443:8443'
      environment:
        - SINGLE_USER_CREDENTIALS_USERNAME=scc413
        - SINGLE_USER_CREDENTIALS_PASSWORD=abcdefghijklm
      volumes:
      #  - ./nifi/conf:/opt/nifi/nifi-current/conf
        - ./adult.json:/opt/nifi/adult.json
        - ./Accuracy.json:/opt/nifi/Accuracy.json
        - ./mysql-connector-j-8.0.32.jar:/opt/nifi/mysql-connector-j-8.0.32.jar
       # - ./adult-census-income.py:/opt/nifi/adult-census-income.py	  
   scc413-grafana:
      image: grafana/grafana:latest
      hostname: scc413-grafana
      container_name: scc413-grafana
      user: '0'
      ports:
          - '3000:3000'
      environment:
         - GF_INSTALL_PLUGINS=marcusolsson-hourly-heatmap-panel
      volumes:
         - ./grafana/var/lib:/var/lib/grafana

   scc413-mysqldb:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: example
      volumes:
        - ./mysql/db.sql:/docker-entrypoint-initdb.d/db.sql
        - ./db_data:/var/lib/mysql
      #command: --secure-file-priv=/home/uploads 
   scc413-adminer:
      image: adminer
      restart: always
      ports:
         - 8080:8080

